export const division = {
  DHAKA: "DHAKA",
  CHITTAGONG: "CHITTAGONG",
  KHULNA: "KHULNA",
  RAJSHAHI: "RAJSHAHI",
  BARISAL: "BARISAL",
  SHYLET: "SHYLET",
  RANGPUR: "RANGPUR",
  MYMENSINGH: "MYMENSINGH",
};
